name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'   # ✅ Replace 'stable' with '18' or 'lts/*'
      - run: npm install
      - run: "echo 'Warning: No tests created yet.'"
